          "id": 1342004,
          "node_id": "MDEyOk9yZ2FuaXphdGlvbjEzNDIwMDQ=",
          "avatar_url": "https://avatars1.githubusercontent.com/u/1342004?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/google",
          "html_url": "https://github.com/google",
          "followers_url": "https://api.github.com/users/google/followers",
          "following_url": "https://api.github.com/users/google/following{/other_user}",
          "gists_url": "https://api.github.com/users/google/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/google/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/google/subscriptions",
          "organizations_url": "https://api.github.com/users/google/orgs",
          "repos_url": "https://api.github.com/users/google/repos",
          "events_url": "https://api.github.com/users/google/events{/privacy}",
          "received_events_url": "https://api.github.com/users/google/received_events",
          "type": "Organization",
          "site_admin": False
        },
        "html_url": "https://github.com/google/firmata.py",
        "description": None,
        "fork": False,
        "url": "https://api.github.com/repos/google/firmata.py",
        "forks_url": "https://api.github.com/repos/google/firmata.py/forks",
        "keys_url": "https://api.github.com/repos/google/firmata.py/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/google/firmata.py/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/google/firmata.py/teams",
        "hooks_url": "https://api.github.com/repos/google/firmata.py/hooks",
        "issue_events_url": "https://api.github.com/repos/google/firmata.py/issues/events{/number}",
        "events_url": "https://api.github.com/repos/google/firmata.py/events",
        "assignees_url": "https://api.github.com/repos/google/firmata.py/assignees{/user}",
        "branches_url": "https://api.github.com/repos/google/firmata.py/branches{/branch}",
        "tags_url": "https://api.github.com/repos/google/firmata.py/tags",
        "blobs_url": "https://api.github.com/repos/google/firmata.py/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/google/firmata.py/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/google/firmata.py/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/google/firmata.py/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/google/firmata.py/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/google/firmata.py/languages",
        "stargazers_url": "https://api.github.com/repos/google/firmata.py/stargazers",
        "contributors_url": "https://api.github.com/repos/google/firmata.py/contributors",
        "subscribers_url": "https://api.github.com/repos/google/firmata.py/subscribers",
        "subscription_url": "https://api.github.com/repos/google/firmata.py/subscription",
        "commits_url": "https://api.github.com/repos/google/firmata.py/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/google/firmata.py/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/google/firmata.py/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/google/firmata.py/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/google/firmata.py/contents/{+path}",
        "compare_url": "https://api.github.com/repos/google/firmata.py/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/google/firmata.py/merges",
        "archive_url": "https://api.github.com/repos/google/firmata.py/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/google/firmata.py/downloads",
        "issues_url": "https://api.github.com/repos/google/firmata.py/issues{/number}",
        "pulls_url": "https://api.github.com/repos/google/firmata.py/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/google/firmata.py/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/google/firmata.py/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/google/firmata.py/labels{/name}",
        "releases_url": "https://api.github.com/repos/google/firmata.py/releases{/id}",
        "deployments_url": "https://api.github.com/repos/google/firmata.py/deployments",
        "created_at": "2013-03-27T23:20:35Z",
        "updated_at": "2019-09-23T11:54:02Z",
        "pushed_at": "2013-03-27T23:34:35Z",
        "git_url": "git://github.com/google/firmata.py.git",
        "ssh_url": "git@github.com:google/firmata.py.git",
        "clone_url": "https://github.com/google/firmata.py.git",
        "svn_url": "https://github.com/google/firmata.py",
        "homepage": None,
        "size": 160,
        "stargazers_count": 15,
        "watchers_count": 15,
        "language": "Python",
        "has_issues": True,
        "has_projects": True,
        "has_downloads": True,
        "has_wiki": True,
        "has_pages": False,
        "forks_count": 15,
        "mirror_url": None,
        "archived": False,
        "disabled": False,
        "open_issues_count": 0,
        "license": {
          "key": "apache-2.0",
          "name": "Apache License 2.0",
          "spdx_id": "Apache-2.0",
          "url": "https://api.github.com/licenses/apache-2.0",
          "node_id": "MDc6TGljZW5zZTI="
        },
        "forks": 15,
        "open_issues": 0,
        "watchers": 15,
        "default_branch": "master",
        "permissions": {
          "admin": False,
          "push": False,
          "pull": True
        }
      }
    ],
    ['episodes.dart', 'cpp-netlib', 'dagger', 'ios-webkit-debug-proxy', 'google.github.io', 'kratu', 'build-debian-cloud', 'traceur-compiler', 'firmata.py'],
    ['dagger', 'kratu', 'traceur-compiler', 'firmata.py'],
  )
]
